#bài 1: Tạo tensor cơ bản
    Yêu cầu: Cho biết kích thước, số chiều và kiểu dữ liệu của Tensor a.
    

In [ ]:
#bài 1: Tạo Tensor cơ bản
import torch
a = torch.tensor(
    [[1, 2, 3], [4, 5, 6]],
    dtype=torch.int32
)

print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


#bài 2: Tạo các Tensor thường dùng
torch.rand() là hàm phân phối đều từ [0,1)
rtorch.randn() là hàm phân phối chuẩn

In [2]:
#bài 2: Tạo các Tensor thường dùng
import torch 

a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2,3)
e = torch.eye(4)
TensorFull10 = torch.full((5, 5), 10)
print(a)
print(b)
print(c)
print(d)
print(e)
print(TensorFull10)

tensor([[0.3955, 0.7988, 0.9777, 0.0807],
        [0.3235, 0.2285, 0.3900, 0.2201],
        [0.6221, 0.5120, 0.1113, 0.6372]])
tensor([[ 1.7727,  1.3845,  0.6970, -0.8157],
        [-0.0213, -1.6673,  0.2234,  1.1242],
        [-1.0061, -0.9779, -0.4555, -1.6432]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


#bài 3: kiểm tra thông tin Tensor 
Yêu cầu: Giải thích ý nghĩa của torch.Size([2,3,4])
- In ra kích thước của tensor 

In [3]:
#bài 3: Kiểm tra thông tin Tensor 
import torch 
a = torch.zeros(2,3,4)
print("Tensor: ")
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)
print(a)


Tensor: 
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


#bài 4: Silicing và indexing
Yêu cầu: Cho biết shape của a[1] và a[1:, 2:4]
Thử lấy hai phần tử cuối cùng trên chiều thứ ba.
 - Shape của a[1] là torch.Size([4, 5]) và a[1:, 2:4] là torch.Size([2, 2, 5])

In [ ]:
#bài 4: slicing và indexing
import torch
a= torch.randn(3,4,5)
print("Original tensor: ")
print(a)

print("\nTensor a[1]:")
print(a[1])

print("\nTensor a[1:, 2:4]: ")
print(a[1:, 2:4])

#lấy 2 phần tử cuối cùng tên chiều thứ 3
print(a[2, -1, -2:])

Original tensor: 
tensor([[[ 2.2528, -0.2379, -0.4079,  0.6199, -0.1327],
         [-1.5239, -0.3235,  2.0108, -0.3040, -0.9557],
         [ 0.3716, -1.2068, -1.2991,  1.0085, -0.4889],
         [ 0.0956, -1.2019, -1.7169,  0.0486,  0.1668]],

        [[ 0.5924, -1.4778,  0.0546, -1.0230, -1.3516],
         [-0.3866,  0.5636, -0.7878,  1.3428,  1.8048],
         [-0.1075,  1.0981, -0.7986, -0.8380,  0.2150],
         [ 0.3221,  0.1340, -1.2118,  0.3303,  1.3450]],

        [[ 0.9642,  0.3306,  0.1929, -0.6094,  0.6378],
         [ 1.0297, -0.4547, -0.1310, -1.1709,  0.1183],
         [ 0.0347, -0.7636,  0.2578, -0.3391,  1.2815],
         [ 1.6773,  1.0068,  0.1934, -0.7728, -0.0047]]])

Tensor a[1]:
tensor([[ 0.5924, -1.4778,  0.0546, -1.0230, -1.3516],
        [-0.3866,  0.5636, -0.7878,  1.3428,  1.8048],
        [-0.1075,  1.0981, -0.7986, -0.8380,  0.2150],
        [ 0.3221,  0.1340, -1.2118,  0.3303,  1.3450]])

Tensor a[1:, 2:4]: 
tensor([[[-0.1075,  1.0981, -0.7986, -0.8380,  0

#bài 5: Reshape và flatten
Yêu cầu: Kiểm tra số phần tử trước và sau khi reshape 
Thử reshape Tensor thành kích thước 2 x 6

In [5]:
#bài 5: reshape và flatten
import torch
a = torch.randn(3, 4)
print('oringinal: ')
print(a)

print('\nFlatten: ')
print(a.ravel())

print('\nreshaped: ')
print(a.reshape(3,2,2 ))

#kiểm tra số phần tử trước và sau khi reshape
print("Trước khi reshape: ", a.numel()," và sau khi reshape: ", a.reshape(3,2,2).numel())
#reshape tensor thành 2 x 6
print("reshape thành 2 x 6: \n", a.reshape(2, 6))

oringinal: 
tensor([[ 0.1092,  0.6469,  1.2232,  0.5500],
        [-0.0220,  1.1284, -1.2003,  0.8243],
        [ 0.6681,  1.4714, -0.9425,  0.1385]])

Flatten: 
tensor([ 0.1092,  0.6469,  1.2232,  0.5500, -0.0220,  1.1284, -1.2003,  0.8243,
         0.6681,  1.4714, -0.9425,  0.1385])

reshaped: 
tensor([[[ 0.1092,  0.6469],
         [ 1.2232,  0.5500]],

        [[-0.0220,  1.1284],
         [-1.2003,  0.8243]],

        [[ 0.6681,  1.4714],
         [-0.9425,  0.1385]]])
Trước khi reshape:  12  và sau khi reshape:  12
reshape thành 2 x 6: 
 tensor([[ 0.1092,  0.6469,  1.2232,  0.5500, -0.0220,  1.1284],
        [-1.2003,  0.8243,  0.6681,  1.4714, -0.9425,  0.1385]])


#bài 6: Phép toán và nhân ma trận
Yêu cầu: Phân biệt phép toán a*b với a@b.T
Cho biết shape của kết quả a@b.T

-  a * b là aij * bij còn a@b.T là a nhân với mà trận chuyển vị của b và theo ý nghĩa đại số tuyến tính
- (a, b)@ ( b,c)= (a, c) (size sau khi nhân a@b)

In [6]:
#bài 6: Phép toán và nhân ma trận
import torch
a=torch.randn(2,3)
b=torch.randn(2,3)
print("a: \n", a)
print("b: \n", b)

print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a: 
 tensor([[ 0.0302, -0.1085, -0.8371],
        [-0.0086,  0.5124,  3.4064]])
b: 
 tensor([[ 0.1416, -0.5720,  0.5291],
        [-0.3779, -1.4834,  0.6128]])

a + b:
tensor([[ 0.1718, -0.6805, -0.3080],
        [-0.3866, -0.9710,  4.0192]])

a / b:
tensor([[ 0.2130,  0.1897, -1.5822],
        [ 0.0228, -0.3454,  5.5592]])

a^2:
tensor([[9.0974e-04, 1.1772e-02, 7.0074e-01],
        [7.4019e-05, 2.6251e-01, 1.1604e+01]])

Matrix multiplication:
tensor([[-0.3766, -0.3634],
        [ 1.5080,  1.3305]])


#bài 7: Các hàm thống kê trên tensor 
dim=0 → theo chiều hàng, thường tính dọc theo các cột
dim=1 → theo chiều cột, thường tính ngang theo các hàng

In [4]:
#bài 7: Các hàm thống kê trên Tensor 
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
#tính độ lệch chuẩn
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[-0.4788,  0.7715,  0.7702,  0.0849],
        [ 1.0755,  0.7558, -0.4816, -1.1107],
        [-0.0091, -1.1787, -0.8209,  0.8716]])

Mean:
tensor([ 0.1958,  0.1162, -0.1774, -0.0514])

Standard deviation:
tensor([0.7972, 1.1214, 0.8381, 0.9981])

Cumulative sum:
tensor([[-0.4788,  0.7715,  0.7702,  0.0849],
        [ 0.5967,  1.5273,  0.2886, -1.0257],
        [ 0.5875,  0.3486, -0.5323, -0.1541]])


#Bài 8: Autograd cơ bản
Yêu cầu: Tính thủ công đạo hàm y = x**2 tại x=3.6 và so sánh với x.grad
Đổi hàm thành y = 3*x**2 + 2*x +1

In [7]:
#bài 8: Autograd cơ bản
import torch
x = torch.tensor(3.6, requires_grad=True)
y = x* x
y.backward()

print("x = ", x)
print("y = ", y)
print("x.grad = ", x.grad)
print("Đạo hàm thủ công: ",3.6*2)
x.grad.zero_()
y = 3*x**2 + 2*x + 1
y.backward()
print("x.grad mới = ", x.grad)
print("Đổi hàm thành: ",y)


x =  tensor(3.6000, requires_grad=True)
y =  tensor(12.9600, grad_fn=<MulBackward0>)
x.grad =  tensor(7.2000)
Đạo hàm thủ công:  7.2
x.grad mới =  tensor(23.6000)
Đổi hàm thành:  tensor(47.0800, grad_fn=<AddBackward0>)


#bài 9: Gradient descent tìm hệ số đa thức
Yêu cầu:
• So sánh ba hệ số học được với [1, 2, 3].
• Giải thích vai trò của optimizer.zero_grad(), mse.backward() và optimizer.step().

In [1]:
#bài 9: Gradient descent tìm hệ số đa thức
import numpy as np
import torch
# tạo đa thức
polynomial = np.poly1d([2, -3, 5])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
#tạo ma trận đặt trưng cho đa thức bậc 2
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()# Xóa gradient cũ
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()# Tính gradient mới, lưu vào w.grad
    optimizer.step()# Dùng gradient để cập nhật w
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[0.6501],
        [0.0860],
        [0.2714]], requires_grad=True)
Learned coefficients:
tensor([[ 2.0319],
        [-3.0333],
        [ 2.8553]], requires_grad=True)


Bài 10. Giải hệ phương trình bằng Autograd
Tối thiểu hóa tổng sai số bình phương để tìm A, B, C, D thỏa bốn phương trình.
Yêu cầu:
• Kiểm tra nghiệm thu được với bốn phương trình: A+B=9, C-D=1, A+C=8, B-D=2.
• Nhận xét vì sao bài toán có thể có nhiều nghiệm.
Bốn phương trình này không độc lập tuyến tính. Phương trình thứ 4 (hoặc bất kỳ phương trình nào) suy ra được từ ba phương trình còn lại:
Từ A + B = 9 và A + C = 8, trừ vế: B − C = 1.
Từ B − D = 2 và C − D = 1, trừ vế: B − C = 1.
Hai kết quả này trùng nhau, nghĩa là hệ chỉ có hạng 3 trong khi có 4 ẩn, nên còn 1 bậc tự do.

In [ ]:
#bài 10: Giải hệ phương trình bằng autograd
import random
import torch
A = torch.tensor(random.random(), requires_grad=True) # tạo ra một số ngẫu nhiên và cho phép tính gradient sau này
B = torch.tensor(random.random(), requires_grad=True)   
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000 # tạo ra 2000 lần lặp để tính toán giá trị tối ưu
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01) # tạo ra một đối tượng optimizer NAdam để sửa A, B, C, D với learning rate = 0.01
for _ in range(EPOCHS): # lập lại quá trình 2000 lần
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4 # tính tổng biến động của y1, y2, y3, y4 và lấy bình phương của nó để tính sqerr
    optimizer.zero_grad() # reset gradient về 0 để gradient cũ không bị cộng vào
    sqerr.backward() # tính gradient của sqerr đối với A, B, C, D
    optimizer.step() # cập nhật giá trị của A, B, C, D dựa trên gradient vừa tính được
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

A = tensor(4.6425, requires_grad=True)
B = tensor(4.3575, requires_grad=True)
C = tensor(3.3575, requires_grad=True)
D = tensor(2.3575, requires_grad=True)


#bài 11: Viết chương trình Pytorch để thực hiện các yêu cầu sau:
• Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.
• Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.
• Cho y = 2x2 + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.
• Thay đa thức trong Bài 9 bằng y = 2x2 - 3x + 5; huấn luyện và cho biết các hệ số tìm được. - Thay giá trị polynomial = np.poly1d([1, 2, 3]) thành 2 -3 5


In [12]:
#bài 11: Viết chương trình Pytorch để thực hiện các yêu cầu
import torch

def tinhtoan(a, b):
    print("a: \n", a)
    print("b: \n", b)
    print("\na + b:", a + b)
    print("\na * b:", a * b)
    print("\na /b:", a / b)
    print("Trung bình theo cột: ", torch.mean(a, dim=0))

x = torch.rand(24)
print(x)
print("Shape 4x6:", x.reshape(4,  6))
print("Shape2x12:", x.reshape(2,12))
print("Shape 2x3x4:", x.reshape(2,3,4))

a, b = torch.rand(3, 4), torch.rand(3, 4)
tinhtoan(a, b)
x =  torch.tensor(2.,requires_grad=True)
y = 2 * x**2 + 5 * x + 3
y.backward()
print("Giá trị y:", y.item())
print("dy/dx bằng autograd:", x.grad.item())

print("Tính thủ công ",2 * 2**2 + 5 * 2 + 3)


tensor([0.8694, 0.4171, 0.9150, 0.2272, 0.3850, 0.0617, 0.5174, 0.2254, 0.7952,
        0.4592, 0.0623, 0.4537, 0.2918, 0.3060, 0.4979, 0.6412, 0.0935, 0.0591,
        0.0941, 0.6777, 0.4791, 0.0295, 0.0157, 0.1581])
Shape 4x6: tensor([[0.8694, 0.4171, 0.9150, 0.2272, 0.3850, 0.0617],
        [0.5174, 0.2254, 0.7952, 0.4592, 0.0623, 0.4537],
        [0.2918, 0.3060, 0.4979, 0.6412, 0.0935, 0.0591],
        [0.0941, 0.6777, 0.4791, 0.0295, 0.0157, 0.1581]])
Shape2x12: tensor([[0.8694, 0.4171, 0.9150, 0.2272, 0.3850, 0.0617, 0.5174, 0.2254, 0.7952,
         0.4592, 0.0623, 0.4537],
        [0.2918, 0.3060, 0.4979, 0.6412, 0.0935, 0.0591, 0.0941, 0.6777, 0.4791,
         0.0295, 0.0157, 0.1581]])
Shape 2x3x4: tensor([[[0.8694, 0.4171, 0.9150, 0.2272],
         [0.3850, 0.0617, 0.5174, 0.2254],
         [0.7952, 0.4592, 0.0623, 0.4537]],

        [[0.2918, 0.3060, 0.4979, 0.6412],
         [0.0935, 0.0591, 0.0941, 0.6777],
         [0.4791, 0.0295, 0.0157, 0.1581]]])
a: 
 tensor([[0.2422, 